name: Bug report
description: Report a problem with the plugin
title: '[Bug]: '
labels: ['bug']
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: Which version of the plugin were you using?
    validations:
      required: true
  - type: input
    id: unraid-version
    attributes:
      label: Unraid Version
      description: Which version of Unraid were you using?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: How can be behavior be recreated?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Tip: You can attach screenshots by clicking this area to highlight it and then dragging files in.
    validations:
      required: false