on:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Template
        run: |
          pip install jinja-cli
          cd tools
          ./build-plugin.sh

      - name: Commit plugin file
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            - plugin/tailscale.plg
            - plugin/tailscale-preview.plg
            - plugin/tailscale-trunk.plg
          default_author: github_actor
