name: Template plugin files

on:
  push:
    branches:
      - trunk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Template
        run: |
          pip install jinja-cli
          cd tools
          ./build-plugin.sh

      - name: Commit plugin file
        run: |
          gh api graphql \
            -F githubRepository=$GITHUB_REPOSITORY \
            -F branchName=$BRANCH \
            -F expectedHeadOid=$(git rev-parse HEAD) \
            -F commitMessage="template: plugin files" \
            -F pluginFile[path]="plugin/tailscale.plg" -F pluginFile[contents]=$(base64 -w0 plugin/tailscale.plg) \
            -F previewFile[path]="plugin/tailscale-preview.plg" -F previewFile[contents]=$(base64 -w0 plugin/tailscale-preview.plg) \
            -F trunkFile[path]="plugin/tailscale-trunk.plg" -F trunkFile[contents]=$(base64 -w0 plugin/tailscale-trunk.plg) \
            -F 'query=@.github/api/createCommitOnBranch.gql'
        env:
          GH_TOKEN: ${{ github.token }}
          BRANCH: "trunk"
