on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Template
        uses: cuchi/jinja2-action@v1.2.2
        with:
          template: tools/plugin/tailscale.j2
          output_file: plugin/tailscale.plg
          data_file: tools/plugin/tailscale.json
          variables: |
            filename=tailscale
            branch=main

      - name: Template
        uses: cuchi/jinja2-action@v1.2.2
        with:
          template: tools/plugin/tailscale.j2
          output_file: plugin/tailscale-preview.plg
          data_file: tools/plugin/tailscale.json
          variables: |
            filename=tailscale-preview
            branch=preview

      - name: Template
        uses: cuchi/jinja2-action@v1.2.2
        with:
          template: tools/plugin/tailscale.j2
          output_file: plugin/tailscale-trunk.plg
          data_file: tools/plugin/tailscale.json
          variables: |
            filename=tailscale-trunk
            branch=trunk

      - name: Commit plugin file
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            - plugin/tailscale.plg
            - plugin/tailscale-preview.plg
            - plugin/tailscale-trunk.plg
          default_author: github_actor
