name: Add main tag to new release
on:
  release:
    types: [published, edited]

jobs:
  run:
    name: Run local action
    runs-on: ubuntu-latest
    if: github.event.release.draft == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Get release info
        run: |
          REPO_NAME=$(echo "${{github.repository}}" | cut -d "/" -f 2)
          RELEASE_JSON=$(gh api graphql \
            -F owner=$RELEASE_OWNER \
            -F name=$REPO_NAME \
            -F tag=$RELEASE_TAG \
            -F 'query=@.github/api/getRelease.gql')

          echo "Info: $RELEASE_JSON"
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_OWNER: ${{ github.repository_owner }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}

      - name: Run latest-tag
        uses: EndBug/latest-tag@v1
        if: |
          github.event.release.prerelease == false
        with:
          ref: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run latest-tag
        uses: EndBug/latest-tag@v1
        with:
          ref: preview
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}