name: Add main tag to new release
on:
  release:
    types: [published, edited]

jobs:
  run:
    name: Run local action
    runs-on: ubuntu-latest
    if: github.event.release.draft == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Get full release object
        run: |
          RELEASE_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}")

          echo "Latest release name: $RELEASE_JSON"

      - name: Run latest-tag
        uses: EndBug/latest-tag@v1
        if: |
          github.event.release.prerelease == false
        with:
          ref: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run latest-tag
        uses: EndBug/latest-tag@v1
        with:
          ref: preview
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}