name: Add main tag to new release
on:
  release:
    types: [published]

jobs:
  run:
    name: Run local action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Run latest-tag
        uses: EndBug/latest-tag@v1
        if: ${{ ! github.event.release.prerelease }}
        with:
          ref: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run latest-tag
        uses: EndBug/latest-tag@v1
        with:
          ref: preview
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}